config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get   'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
resources :users do
      member do
        get :following, :followers
      end
    end
resources :conversations, only: [:index, :show, :new, :create] do
   member do
     post :reply
     post :trash
     post :untrash
   end
 end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :comments
  resources :likes

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :logged_in_user
  helper_method :mailbox, :conversation

  def create
    recipient_name = conversation_params(:recipients).split(',')
    recipients = User.where(name: recipient_name).all
    conversation = current_user.
      send_message(recipients, *conversation_params(:body, :subject)).conversation

    conversation.participants.each do |notifier|
      if notifier.name != current_user.name
        @reciver = notifier
      end
    end
      @reciver.notify(@reciver.id,"You got a new message from #{current_user.name}")
    redirect_to conversation_path(conversation)
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    conversation.participants.each do |notifier|
      if notifier.name != current_user.name
        @reciver = notifier
      end
    end 
    if request.original_url != conversation_path(conversation)
      @reciver.notify(@reciver.id,"You got a new replay from #{current_user.name}")
    end

    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/views/conversations/_conversation.html.erb
<%= content_tag_for(:li, conversation) do |conversation| %>
  <p>
    <% conversation.participants.each do |recipient|%>
      <% if recipient != current_user %>
      <%= image_tag recipient.avatar, size: '100x80' %>
    <%= link_to  recipient.name, user_path(recipient) %>
    <% end %>
    <% end %>
    |
    <%= link_to conversation.subject, conversation_path(conversation) %>
    |
    <% if conversation.is_completely_trashed?(current_user) %>
      <%= link_to 'Untrash', untrash_conversation_path(conversation), method: :post %>
    <% else %>
      <%= link_to 'Move to trash', trash_conversation_path(conversation), method: :post %>
    <% end %>


  </p>
<% end %>

app/views/conversations/_form.html.erb
<div >
<%= form_for :conversation, url: :conversations do |f| %>
  <%= f.hidden_field :recipients, value: @user.name %>
  <%= f.text_field :subject, placeholder: 'Type message subject'%>
  <%= f.text_area :body, placeholder: 'Type message'%>
  <%= f.submit 'Submit', class: 'btn-primary'%>
  <%= f.submit 'Cancel', type: :reset, class: 'btn-danger'%>
<% end %>

</div>

app/views/conversations/index.html.erb
<h1> Conversations</h1>
<h2>Inbox</h2>
<ul>
  <%=  render collection: mailbox.inbox, partial: 'conversation' %>
</ul>
<h2>Sentbox</h2>
<ul>
  <%= render collection: mailbox.sentbox, partial: 'conversation' %>
</ul>
<h2>Trash</h2>
<ul>
  <%= render collection: mailbox.trash, partial: 'conversation' %>
</ul>

<%= link_to 'Start Conversation', :new_conversation %>

app/views/conversations/new.html.erb
<h1> Start Conversation</h1>
<%= render 'form' %>

app/views/conversations/show.html.erb
<% if conversation.participants[0].name == current_user.name  %>
<div class="conv_header">
  <h1 style="display: inline-block"><%= conversation.participants[1].name %></h1>
  <%= image_tag conversation.participants[1].avatar, size: '100x80',:style => 'display: inline-block' %>
</div>

<% else %>
<h1><%= conversation.participants[0].name %></h1>
<%= image_tag conversation.participants[0].avatar, size: '100x80',:style => 'display: inline-block' %>
<% end %>
<ul>
  <%= content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt| %>

    <% message = receipt.message%>
    <% if message.sender_id == current_user.id %>
    <% @align = 'moi' %>
    <% else %>
    <% @align = 'sender' %>
    <% end %>
<div class="message_bubble <%= @align %>">
  <p>
    <% if message.sender_id  != current_user.id %>
    <%= image_tag User.find(message.sender_id).avatar, size: '40x40' %>
    <% end %>
    <%= message.body %>
    </p>
</div>



<% end %>
</ul>
<%= render 'messages/form', conversation: conversation%>